name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install melos and initialize workspace
        uses: bluefireteam/melos-action@v3
        with:
          melos-version: '^6.0.0'

      - name: Lint
        run: melos format --output none --set-exit-if-changed

      - name: Analyze
        run: melos analyze
